import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("PersonaCardShelf keeps inspect separate from insert and exposes stagger/reduced-motion contracts", async () => {
  const source = await readFile(new URL("../app/persona-card-shelf.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/persona-card-shelf.module.css", import.meta.url), "utf8");
  const modelSource = await readFile(new URL("../app/persona-card-model.ts", import.meta.url), "utf8");
  const faceSource = await readFile(new URL("../app/persona-card-face.tsx", import.meta.url), "utf8");
  const backSource = await readFile(new URL("../app/persona-card-back.tsx", import.meta.url), "utf8");
  const backCss = await readFile(new URL("../app/persona-card-back.module.css", import.meta.url), "utf8");
  assert.match(source, /cards: readonly PersonaCard\[\]/);
  assert.match(source, /onInspect: \(cardId: string\) => void/);
  assert.match(source, /onCreateFromTemplate\?: \(template: PersonaCard\) => void/);
  assert.match(source, /onManage\?: \(\) => void/);
  assert.match(source, /onManage \? <button/);
  assert.match(source, /PersonaManagementPage/);
  assert.doesNotMatch(source, /card-management/);
  assert.doesNotMatch(source, /张卡牌/);
  assert.match(source, /onDragStart/);
  assert.match(source, /onDragEnd\?:/);
  assert.match(source, /onDragEnd\?\.\(event\)/);
  assert.match(source, /onManage\?: \(\) => void/);
  assert.match(source, /onDragStart\?: \(item: PersonaCardDragItem/);
  assert.match(source, /entranceKey/);
  assert.match(source, /className=\{styles\.inspectButton\}/);
  assert.match(source, /onClick=\{\(event\) =>/);
  assert.match(source, /<article/);
  assert.doesNotMatch(source, /<article[^>]*onClick/);
  assert.match(source, /data-persona-card-inspect/);
  assert.match(source, /className=\{styles\.dragSurface\}/);
  assert.match(source, /onPointerDown=\{\(event\) => beginDrag/);
  assert.match(source, /onPointerUp=\{\(event\) => finishDrag/);
  assert.match(source, /onPointerCancel=\{\(event\) => finishDrag/);
  assert.match(source, /event\.stopPropagation\(\)/);
  const finishDragBlock = source.slice(source.indexOf("function finishDrag"), source.indexOf("\n\n  return"));
  assert.doesNotMatch(finishDragBlock, /event\.preventDefault|event\.stopPropagation/);
  assert.match(source, /Page owns the drag\/drop transaction/);
  assert.equal((source.match(/<button/g) ?? []).length, 3);
  assert.doesNotMatch(source, /serial/);
  assert.doesNotMatch(source, /onInsert/);
  assert.match(source, /quickPopover/);
  assert.match(source, /popoverSuppressedId/);
  assert.match(source, /setPopoverSuppressedId/);
  assert.match(css, /pointer-events: none/);
  assert.match(css, /bottom: 40%/);
  assert.match(css, /\.popoverSuppressed \.quickPopover/);
  assert.match(css, /grid-template-columns: repeat\(5/);
  assert.match(css, /object-fit: contain/);
  assert.match(css, /object-position: 50% 20%/);
  assert.match(css, /masked-v2 is a half-body portrait/);
  assert.match(css, /backdrop-filter: blur/);
  assert.match(css, /animation-delay: calc\(var\(--card-index\) \* 70ms\)/);
  assert.match(css, /z-index: var\(--layer-overlay/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(source, /normalizePersonaCardCollection/);
  assert.match(source, /isTemplate \? <PersonaCardFace card=\{card\}>/);
  assert.match(source, /className=\{`\$\{styles\.inspectButton\} \$\{styles\.emptySlotButton\}`\}/);
  assert.doesNotMatch(faceSource, />人</);
  assert.match(css, /\.emptyArt i/);
  assert.match(source, /onCreateFromTemplate\?\.\(card\)/);
  assert.match(source, /PersonaCardFace/);
  assert.doesNotMatch(source, /PersonaBrandMark|<svg|◇|菱形/);
  assert.match(modelSource, /custom-template-empty-v1/);
  assert.match(modelSource, /name: "新建角色卡"/);
  assert.match(modelSource, /role: "空白角色位"/);
  assert.equal((modelSource.match(/templateId: "empty"/g) ?? []).length, 1);
  assert.match(css, /animation: none/);
  assert.match(css, /pointer-events: none/);
  assert.match(faceSource, /PERSONA_CARD_BRAND_LOGO_SRC/);
  assert.match(faceSource, /persona-gate-logo-v1-64\.png/);
  assert.match(faceSource, /aria-hidden="true"/);
  assert.doesNotMatch(faceSource, /<svg|PersonaCardIcon/);
  assert.match(backSource, /PERSONA_CARD_BRAND_LOGO_SRC/);
  assert.doesNotMatch(backSource, /persona-card-back-base|wordmark|假面骑事/);
  assert.equal((backSource.match(/<img/g) ?? []).length, 1);
  assert.equal((faceSource.match(/persona-gate-logo-v1-64\.png/g) ?? []).length, 1);
  assert.match(faceSource, /persona-gate-logo-v1-64\.png/);
  assert.doesNotMatch(backSource, /<svg|◇|菱形|PersonaCardIcon/);
  assert.match(backCss, /pointer-events: none/);
});

test("PersonaCard exposes one generic empty slot and keeps it unmapped", async () => {
  const model = await readFile(new URL("../app/persona-card-model.ts", import.meta.url), "utf8");
  assert.match(model, /PERSONA_CARD_TEMPLATE_CARDS/);
  assert.match(model, /templateId: "empty"/);
  assert.equal((model.match(/templateId: "empty"/g) ?? []).length, 1);
  assert.match(model, /skillBinding: \{ status: "unmapped" \}/);
});

test("PersonaDetailSheet exposes only motion and art-preview actions with a closable lightbox", async () => {
  const source = await readFile(new URL("../app/persona-detail-sheet.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/persona-detail-sheet.module.css", import.meta.url), "utf8");
  const icons = await readFile(new URL("../app/persona-card-icons.tsx", import.meta.url), "utf8");
  assert.match(source, /card: PersonaCard \| null/);
  assert.match(source, /open: boolean/);
  assert.match(source, /Open state is page-owned/);
  assert.match(source, /onClose: \(\) => void/);
  assert.doesNotMatch(source, /setOpen|setCard|setNaviRun|setManifested/);
  assert.doesNotMatch(source, /onEdit|onInsert|onAdd|onAnnounce|Skill 已验证|复制后编辑|插入卡片|新建空卡|播报英文名/);
  assert.match(source, /event\.key === "Escape"/);
  assert.match(source, /event\.key !== "Tab"/);
  assert.match(source, /restoreFocusRef\.current\?\.focus\(\)/);
  assert.match(source, /role="dialog"/);
  assert.match(source, /aria-modal="true"/);
  assert.match(source, /aria-labelledby="persona-detail-sheet-title"/);
  assert.match(source, /className=\{styles\.backdrop\}/);
  assert.match(source, /播放人物动画/);
  assert.match(source, /放大查看立绘/);
  assert.match(source, /previewMode === "motion"/);
  assert.match(source, /className=\{styles\.lightboxBackdrop\}/);
  assert.match(source, /aria-label="关闭预览"/);
  assert.match(css, /width: min\(420px/);
  assert.match(css, /z-index: var\(--layer-hands/);
  assert.match(css, /backdrop-filter/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(icons, /viewBox: "0 0 24 24"/);
  assert.match(icons, /stroke: "currentColor"/);
  for (const iconId of ["naval", "musk", "jobs", "trump", "pg"]) assert.match(icons, new RegExp(`iconId === "${iconId}"`));
});
